const fakeDB = [
  {
    idDrink: "12720",
    strDrink: "Kill the cold Smoothie",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Other/Unknown",
    strIBA: null,
    strAlcoholic: "Non alcoholic",
    strGlass: "Highball glass",
    strInstructions:
      "Juice ginger and lemon and add it to hot water. You may add cardomom.",
    strInstructionsES: null,
    strInstructionsDE:
      "Ingwer und Zitrone entsaften und in heißes Wasser geben. Du kannst Cardomom hinzufügen.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Spremere lo zenzero e il limone e aggiungerlo all'acqua calda.Puoi aggiungere il cardamomo.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/7j1z2e1487603414.jpg",
    strIngredient1: "Ginger",
    strIngredient2: "Lemon",
    strIngredient3: "Water",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 inch ",
    strMeasure2: "1/4 ",
    strMeasure3: "1 cup hot ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-02-20 15:10:15",
  },
  {
    idDrink: "12362",
    strDrink: "Tequila Fizz",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Ordinary Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Collins glass",
    strInstructions:
      "Shake all ingredients (except ginger ale) with ice and strain into a collins glass over ice cubes. Fill with ginger ale, stir, and serve.",
    strInstructionsES: null,
    strInstructionsDE:
      "Alle Zutaten (außer Ginger Ale) mit Eis schütteln und in ein Collins-Glas über Eiswürfel abseihen. Mit Ginger Ale füllen, umrühren und servieren.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Shakerare tutti gli ingredienti (eccetto ginger ale) con ghiaccio e filtrare in un bicchiere Collins con cubetti di ghiaccio.Riempi con ginger ale, mescola e servi.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/2bcase1504889637.jpg",
    strIngredient1: "Tequila",
    strIngredient2: "Lemon juice",
    strIngredient3: "Grenadine",
    strIngredient4: "Egg white",
    strIngredient5: "Ginger ale",
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 oz ",
    strMeasure2: "1 tblsp ",
    strMeasure3: "3/4 oz ",
    strMeasure4: "1 ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-08 17:53:57",
  },
  {
    idDrink: "13625",
    strDrink: "Screaming Orgasm",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Ordinary Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Pour first vodka, then Bailey's, then Kahlua into a cocktail glass over crushed ice. Stir. Caution: use only high quality vodka. Cheap vodka can cause the Bailey's to curdle. Test your brand of vodka by mixing 1 Tsp each of vodka and Bailey's first.",
    strInstructionsES: null,
    strInstructionsDE:
      "Gießen Sie zuerst Wodka, dann Bailey's, dann Kahlua in ein Cocktailglas über zerstoßenes Eis. Rühren. Achtung: Verwenden Sie nur hochwertigen Wodka. Billiger Wodka kann dazu führen, dass der Bailey's gerinnt. Testen Sie Ihre Wodka-Marke, indem Sie jeweils 1 Teelöffel Wodka und einen Teelöffel Bailey's mischen.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Versare la prima vodka, poi la Bailey's, poi Kahlua in un bicchiere da cocktail su ghiaccio tritato.\r\nAgitare.\r\nAttenzione: usa solo vodka di alta qualità.\r\nLa vodka economica può far inasprire il Bailey's.\r\nMetti alla prova la tua marca di vodka mescolando 1 cucchiaino ciascuno di vodka e il primo di Bailey.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/x894cs1504388670.jpg",
    strIngredient1: "Vodka",
    strIngredient2: "Baileys irish cream",
    strIngredient3: "Kahlua",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 oz ",
    strMeasure2: "1 1/2 oz ",
    strMeasure3: "1/2 oz ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-02 22:44:30",
  },
  {
    idDrink: "15409",
    strDrink: "Danbooka",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Coffee / Tea",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Coffee Mug",
    strInstructions: "pour it in and mix it.",
    strInstructionsES: null,
    strInstructionsDE: "Einfüllen und vermengen.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Versare tutti gli ingredienti in un bicchiere, mescola bene.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/vurrxr1441246074.jpg",
    strIngredient1: "Coffee",
    strIngredient2: "Everclear",
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "3 parts ",
    strMeasure2: "1 part ",
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2015-09-03 03:07:55",
  },
  {
    idDrink: "12704",
    strDrink: "Limeade",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Other/Unknown",
    strIBA: null,
    strAlcoholic: "Non alcoholic",
    strGlass: "Highball glass",
    strInstructions:
      "In a large glass, put the lime juice and sugar, and stir well. Add cold seltzer water to fill. Put the lime peels in the glass. Drink. Repeat until limes or soda run out.",
    strInstructionsES: null,
    strInstructionsDE:
      "In einem großen Glas Limettensaft und Zucker anrühren. Füge kaltes Selterswasser zum Befüllen hinzu. Die Limettenschalen in das Glas geben. Trink. Wiederholen Sie dies, bis Limetten oder Soda aufgebraucht sind.",
    strInstructionsFR: null,
    strInstructionsIT:
      "In un bicchiere grande mettere il succo di lime e lo zucchero e mescolare bene. Aggiungere acqua fredda di seltz per riempire. Ripeti finché i lime o la soda non si esauriscono. Mettere le bucce di lime nel bicchiere.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/5jdp5r1487603680.jpg",
    strIngredient1: "Lime",
    strIngredient2: "Sugar",
    strIngredient3: "Soda water",
    strIngredient4: "Lime peel",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "Juice of 1 ",
    strMeasure2: "1 tblsp ",
    strMeasure3: " (seltzer water)\n",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-02-20 15:14:40",
  },
];

export default fakeDB;
